# Generated by Django 5.1.6 on 2025-03-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_task_completed_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
